[profile.release]
overflow-checks = true
lto = true
opt-level = 3

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[registry]
name = "peaceleague"
url = "https://github.com/peaceleagueafrica"
edition = "2021"